title: kirc | KISS for IRC
logo: kirc.png
description: A tiny IRC client written in POSIX C99.
theme: jekyll-theme-minimal
show_downloads: true
author:
  name: "Michael Czigler"
  email: "info@kirc.chat"
